#!/bin/sh

exec mongod \
	--nohttpinterface \
	--noprealloc \
	--nojournal \
	--smallfiles \
	--nssize=1 \
	--oplogSize=1 \
	--shardsvr \
	--dbpath ./db \
	--replSet rs3 \
	--bind_ip=127.0.0.1 \
	--port 40032 \
	--keyFile=../../keyfile
