language: go

go_import_path: gopkg.in/mgo.v2-unstable

addons:
    apt:
        packages:
            - libsensor4
            - gcc
            - g++

env:
    global:
        - BUCKET=https://niemeyer.s3.amazonaws.com
    matrix:
        #- MONGO=mongodb-linux-x86_64-subscription-ubuntu1204-2.2.6
        #- MONGO=mongodb-linux-x86_64-subscription-ubuntu1204-2.4.13
        - MONGO=mongodb-linux-x86_64-enterprise-ubuntu1404-2.6.10
        - MONGO=mongodb-linux-x86_64-enterprise-ubuntu1404-3.0.8

install:
    - wget $BUCKET/$MONGO.tgz
    - tar xzvf $MONGO.tgz
    - export PATH=$PWD/$MONGO/bin:$PATH

    - wget $BUCKET/daemontools.tar.gz
    - tar xzvf daemontools.tar.gz
    - export PATH=$PWD/daemontools:$PATH

    - wget $BUCKET/libnetsnmp.tar.gz
    - tar xzvf libnetsnmp.tar.gz
    - export LD_LIBRARY_PATH=$PWD/libnetsnmp:$LD_LIBRARY_PATH

    - go get gopkg.in/check.v1
    - go get gopkg.in/yaml.v2

before_script:
    - make startdb

script:
    - (cd bson && go test -check.v)
    - go test -check.v -fast


# vim:sw=4:ts=4:et
