language: go

go_import_path: gopkg.in/mgo.v2

addons:
    apt:
        packages:
            - daemontools

services:
    - mongodb

before_script:
    - make startdb

script:
    - cd bson && go test -check.v
    - go test -check.v -fast

# vim:sw=4:ts=4:et
