language: go

go_import_path: gopkg.in/mgo.v2

addons:
    apt:
        packages:
            - daemontools

services:
    - mongodb

env:
    global:

before_script:
    - wget https://niemeyer.s3.amazonaws.com/daemontools.tar.gz
    - tar xzvf daemontools.tar.gz
    - daemontools/svc
    - export PATH=$PWD/daemontools:$PATH
    - make startdb

script:
    - cd bson && go test -check.v
    - go test -check.v -fast

# vim:sw=4:ts=4:et
