language: go

go_import_path: gopkg.in/mgo.v2-unstable

#sudo: required
#dist: trusty

addons:
    apt:
        packages:
            #- libsensors4
            #- libsnmp30

env:
    global:
        - BUCKET=https://niemeyer.s3.amazonaws.com
    matrix:
        - GO=1.4.1 MONGO=mongodb-linux-x86_64-2.2.7
        - GO=1.4.1 MONGO=mongodb-linux-x86_64-2.4.14
        - GO=1.4.1 MONGO=mongodb-linux-x86_64-2.6.11
        - GO=1.4.1 MONGO=mongodb-linux-x86_64-3.0.9
        - GO=1.4.1 MONGO=mongodb-linux-x86_64-3.2.3-nojournal
        - GO=1.5.3 MONGO=mongodb-linux-x86_64-3.0.9
        - GO=1.6   MONGO=mongodb-linux-x86_64-3.0.9

install:
    - eval $(gimme $GO)

    #- export DEBIAN_FRONTEND=noninteractive
    #- sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libsnmp30

    - wget $BUCKET/$MONGO.tgz
    - tar xzvf $MONGO.tgz
    - export PATH=$PWD/$MONGO/bin:$PATH

    - wget $BUCKET/daemontools.tar.gz
    - tar xzvf daemontools.tar.gz
    - export PATH=$PWD/daemontools:$PATH

    #- wget $BUCKET/libnetsnmp.tar.gz
    #- tar xzvf libnetsnmp.tar.gz
    #- export LD_LIBRARY_PATH=$PWD/libnetsnmp:$LD_LIBRARY_PATH

    - go get gopkg.in/check.v1
    - go get gopkg.in/yaml.v2

before_script:
    - export NOIPV6=1
    - make startdb

script:
    - (cd bson && go test -check.v)
    - go test -check.v -fast


# vim:sw=4:ts=4:et
