#!/bin/sh

exec mongod \
	--nohttpinterface \
	--noprealloc \
	--nojournal \
	--smallfiles \
	--nssize=1 \
	--oplogSize=1 \
	--dbpath $PWD/db \
	--bind_ip=127.0.0.1 \
	--port 40103 \
	--configsvr \
	--auth \
	--keyFile=../../keyfile
